### ISSUE TITLE
Can't login to 'real' account

### ISSUE THREAD

**Issue by NoHacksJustRetro** [BtoBastian/Javacord#197]
java.lang.IllegalArgumentException: 400 Bad request! Maybe wrong email or password? StatusText: BAD REQUEST; Body: {"captcha_key":["captcha-required"]}
        at de.btobastian.javacord.ImplDiscordAPI.requestTokenBlocking(ImplDiscordAPI.java:804)
        at de.btobastian.javacord.ImplDiscordAPI.connectBlocking(ImplDiscordAPI.java:157)
        at de.btobastian.javacord.ImplDiscordAPI$2.call(ImplDiscordAPI.java:145)
        at de.btobastian.javacord.ImplDiscordAPI$2.call(ImplDiscordAPI.java:142)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Vampire** [comment]
Well, according to the error message a captcha is required. You should maybe use your token instead of username / password. But be aware, no matter whether you use username / password or user token, what you do is against the ToS of Discord and will most likely get your account banned very fast? Besides that I'd recommend using v3 instead of v2. There username / password is not even possible as Discord requested it to be removed from libs.

**Comment by BoneyIsSpooky** [comment]
Logging in without a bot token is deprecated and will get your Discord account disabled.
Requesting this issue be closed.
