### ISSUE TITLE
Uncached user in MessageReactionAddHandler

### ISSUE THREAD

**Issue by BtoBastian** [BtoBastian/Javacord#248]
Reported by a user on Discord.

```java
15:49:13.524 [main] DEBUG de.btobastian.javacord.DiscordApiBuilder - Creating shard 0 of 1
15:49:14.126 [Javacord - Central ExecutorService - 2] DEBUG de.btobastian.javacord.utils.rest.RestRequest - Trying to send GET request to https://discordapp.com/api/v6/gateway
15:49:14.776 [Javacord - Central ExecutorService - 2] DEBUG de.btobastian.javacord.utils.rest.RestRequest - Sent GET request to https://discordapp.com/api/v6/gateway and received status code 200 with body {"url": "wss://gateway.discord.gg"}
15:49:14.793 [Javacord - Central ExecutorService - 2] DEBUG de.btobastian.javacord.utils.ratelimits.RatelimitManager - Calculated an offset of -776 to the Discord time.
15:49:15.428 [ReadingThread] DEBUG de.btobastian.javacord.utils.DiscordWebSocketAdapter - Received HELLO packet
15:49:15.432 [Javacord - Central Scheduler - 1] DEBUG de.btobastian.javacord.utils.DiscordWebSocketAdapter - Sent heartbeat (interval: 41250)
15:49:15.432 [ReadingThread] DEBUG de.btobastian.javacord.utils.DiscordWebSocketAdapter - Sending identify packet
15:49:15.610 [ReadingThread] DEBUG de.btobastian.javacord.utils.DiscordWebSocketAdapter - Heartbeat ACK received
15:49:15.750 [ReadingThread] DEBUG de.btobastian.javacord.utils.DiscordWebSocketAdapter - Received READY packet
15:49:19.176 [Javacord - Central ExecutorService - 1] DEBUG de.btobastian.javacord.utils.rest.RestRequest - Trying to send POST request to https://discordapp.com/api/v6/channels/<removed>/messages with body {"content":"I'm online now!","tts":false,"mentions":[]}
15:49:19.464 [Javacord - Central ExecutorService - 1] DEBUG de.btobastian.javacord.utils.rest.RestRequest - Sent POST request to https://discordapp.com/api/v6/channels/<removed>/messages and received status code 200 with body {"nonce": null, "attachments": [], "tts": false, "embeds": [], "timestamp": "2018-03-09T13:49:19.323000+00:00", "mention_everyone": false, "id": "<removed>", "pinned": false, "edited_timestamp": null, "author": {"username": "<removed>", "discriminator": "<removed>", "id": "<removed>", "avatar": "<removed>"}, "mention_roles": [], "content": "I'm online now!", "channel_id": "<removed>", "mentions": [], "type": 0}
15:49:19.465 [Javacord - Central ExecutorService - 1] DEBUG de.btobastian.javacord.utils.ratelimits.RatelimitManager - Calculated an offset of -465 to the Discord time.
15:49:56.683 [Javacord - Central Scheduler - 1] DEBUG de.btobastian.javacord.utils.DiscordWebSocketAdapter - Sent heartbeat (interval: 41250)
15:49:56.846 [ReadingThread] DEBUG de.btobastian.javacord.utils.DiscordWebSocketAdapter - Heartbeat ACK received
15:50:37.934 [Javacord - Central Scheduler - 1] DEBUG de.btobastian.javacord.utils.DiscordWebSocketAdapter - Sent heartbeat (interval: 41250)
15:50:38.132 [ReadingThread] DEBUG de.btobastian.javacord.utils.DiscordWebSocketAdapter - Heartbeat ACK received
15:50:50.126 [Javacord - 'handlers' Processor] WARN de.btobastian.javacord.utils.PacketHandler - Couldn't handle packet of type MESSAGE_REACTION_ADD. Please contact the developer! (packet: {"user_id":"<removed>","message_id":"<removed>","emoji":{"name":"<removed>","id":"<removed>","animated":false},"channel_id":"<removed>"})
java.lang.NullPointerException: null
	at de.btobastian.javacord.utils.handler.message.reaction.MessageReactionAddHandler.lambda$null$0(MessageReactionAddHandler.java:48)
	at java.util.Optional.ifPresent(Unknown Source)
	at de.btobastian.javacord.utils.handler.message.reaction.MessageReactionAddHandler.lambda$handle$2(MessageReactionAddHandler.java:48)
	at java.util.Optional.ifPresent(Unknown Source)
	at de.btobastian.javacord.utils.handler.message.reaction.MessageReactionAddHandler.handle(MessageReactionAddHandler.java:35)
	at de.btobastian.javacord.utils.PacketHandler.lambda$handlePacket$0(PacketHandler.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Important detail: It's a user account.

**Comment by BtoBastian** [comment]
https://github.com/BtoBastian/Javacord/commit/ee48ce1568424af8f8be46603521f43a059b5cda
This commit should fix it.
