### ISSUE TITLE
New error when getting network connection problem

### ISSUE THREAD

**Issue by nguyenquyhy** [BtoBastian/Javacord#39]
After updating to the latest development code, it seems to show up 4 times everytime there is connection issue.

[03:39:48] [WritingThread/WARN] [de.btobastian.javacord.utils.DiscordWebsocketAdapter/sponge]: Websocket error!
com.neovisionaries.ws.client.WebSocketException: Flushing frames to the server failed: Connection closed by remote host
	at com.neovisionaries.ws.client.WritingThread.doFlush(WritingThread.java:436) [WritingThread.class:?]
	at com.neovisionaries.ws.client.WritingThread.sendFrames(WritingThread.java:386) [WritingThread.class:?]
	at com.neovisionaries.ws.client.WritingThread.main(WritingThread.java:110) [WritingThread.class:?]
	at com.neovisionaries.ws.client.WritingThread.run(WritingThread.java:57) [WritingThread.class:?]
Caused by: java.net.SocketException: Connection closed by remote host
	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1555) ~[?:1.8.0_111]
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71) ~[?:1.8.0_111]
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[?:1.8.0_111]
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[?:1.8.0_111]
	at java.io.FilterOutputStream.flush(FilterOutputStream.java:140) ~[?:1.8.0_111]
	at com.neovisionaries.ws.client.WritingThread.flush(WritingThread.java:273) ~[WritingThread.class:?]
	at com.neovisionaries.ws.client.WritingThread.doFlush(WritingThread.java:424) ~[WritingThread.class:?]
	... 3 more

**Comment by BtoBastian** [comment]
Hey,

is this really the latest version on the dev branch?
This commit: https://github.com/BtoBastian/Javacord/commit/6120ee92a4d1a99297e036ace895c857a2e8a1e0 should have fixed this bug already. My bot is using this patch for the last 20 hours without any errors.

**Comment by nguyenquyhy** [comment]
Let me pull again, maybe I pull a bit too early.

**Comment by BtoBastian** [comment]
Hey,
Version 2.0.14 has been released. This version should be very stable.
