### ISSUE TITLE
Bug at startup 

### ISSUE THREAD

**Issue by SunnyElite** [BtoBastian/Javacord#55]
`22:09:50.385 [pool-4-thread-1] WARN de.btobastian.javacord.utils.PacketHandler - Couldn't handle packet of type VOICE_STATE_UPDATE. Please contact the developer! (packet: {"self_deaf":false,"user_id":"296277025944240150","guild_id":"275392071336984578","deaf":false,"session_id":"c485186050a4af91bbb22f8014775ab2","mute":false,"suppress":false,"self_video":false,"self_mute":false,"channel_id":"291808178411274240"})
java.lang.NullPointerException: null
	at de.btobastian.javacord.utils.handler.voice.VoiceStateUpdateHandler.handle(VoiceStateUpdateHandler.java:79)
	at de.btobastian.javacord.utils.PacketHandler$1.run(PacketHandler.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)`

I'm using version 2.0.14-4

**Comment by BtoBastian** [comment]
Fixed :)
