### ISSUE TITLE
Couldn't handle packet of type READY when used as self bot

### ISSUE THREAD

**Issue by quantumcat1** [BtoBastian/Javacord#83]
Everything works swimmingly when connecting with a bot token. But there is an exception in PacketHandler.java when it connects as a user. To try and troubleshoot I went back to the basic ping pong example, assuming that would work and I would have to work out what was wrong with my thing. But it still had the same problem. If I connect with a bot account it works fine, but it won't work with either an email and password or with my token. I guess this is probably more of a support issue, because if it wasn't possible to connect using a user account someone would have noticed by now. Do you know what I might have wrong?

This is the console output:
`Sep 01, 2017 1:15:22 PM de.btobastian.javacord.utils.JavacordLogger info
INFO: No SLF4J compatible logger was found. Using default javacord implementation!
Sep 01, 2017 1:15:26 PM de.btobastian.javacord.utils.JavacordLogger warn
WARNING: Couldn't handle packet of type READY. Please contact the developer! (packet:<snip: seems to have personal data>
java.lang.NullPointerException
	at de.btobastian.javacord.entities.impl.ImplServer.<init>(ImplServer.java:187)
	at de.btobastian.javacord.utils.handler.ReadyHandler.handle(ReadyHandler.java:53)
	at de.btobastian.javacord.utils.PacketHandler.handlePacket(PacketHandler.java:80)
	at de.btobastian.javacord.utils.DiscordWebsocketAdapter.onTextMessage(DiscordWebsocketAdapter.java:168)
	at de.btobastian.javacord.utils.DiscordWebsocketAdapter.onBinaryMessage(DiscordWebsocketAdapter.java:259)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:272)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:992)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:751)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110)
	at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66)
`

And this is my code (basically identical to the ping pong example):
```
package main;

import de.btobastian.javacord.DiscordAPI;
import de.btobastian.javacord.Javacord;
import de.btobastian.javacord.entities.message.Message;
import de.btobastian.javacord.listener.message.MessageCreateListener;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import com.google.common.util.concurrent.FutureCallback;

public class Main
{
	static String botToken;
	static String myToken = (snip)
	static String email = (snip)
	static String password = (snip)

	public static void main(String[] args)
	{
		ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
		try (InputStream input = classLoader.getResourceAsStream("config.properties")) {
			Properties prop = new Properties();
			prop.load(input);
			botToken = prop.getProperty("test token");
		} catch (IOException e) {
			e.printStackTrace();
		}


		//DiscordAPI api = Javacord.getApi(email, password); //doesn't work
		DiscordAPI api = Javacord.getApi(myToken, false); //doesn't work
		//DiscordAPI api = Javacord.getApi(botToken, true); //works fine
		api.connect(new FutureCallback<DiscordAPI>()
		{
			@Override
			public void onSuccess(DiscordAPI api)
			{
				api.registerListener(new MessageCreateListener()
				{
					@Override
					public void onMessageCreate(DiscordAPI api, Message message)
					{
						if(message.getContent().equals("ping"))
						{
							message.reply("pong");
						}
					}
				});
			}
			@Override
			public void onFailure(Throwable t)
			{
				t.printStackTrace();
			}
		});
	}
}
```

Edit: it is actually running, but can't write replies. When it tries (after message.reply("pong")) this is the console output:
`Sep 01, 2017 1:41:51 PM de.btobastian.javacord.utils.JavacordLogger warn
WARNING: Uncaught exception in MessageCreateListener!
java.lang.NullPointerException
	at de.btobastian.javacord.entities.message.impl.ImplMessage.reply(ImplMessage.java:402)
	at main.Main$1$1.onMessageCreate(Main.java:48)
	at de.btobastian.javacord.utils.handler.message.MessageCreateHandler$1.run(MessageCreateHandler.java:66)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

**Comment by Mysterypotatoguy** [comment]
It'd be appreciated if you could post the packet you received in the first example, removing the email if you need to.

**Comment by BtoBastian** [comment]
Taking a look at the line of the error, it's most likely related to this issue: https://github.com/BtoBastian/Javacord/issues/82
Should be easily fixed when I'm back home from vacation.

**Comment by quantumcat1** [comment]
I'll email the packet if anyone needs me to, but I'd rather not publish it as it seems to have info about every Discord server and channel I am in as well as who I have DMs with, and I think my token.

**Comment by BtoBastian** [comment]
Please check, if this error still exists in version 2.0.17.
