### ISSUE TITLE
Error when running example code

### ISSUE THREAD

**Issue by RaphaelBunck** [BtoBastian/Javacord#87]
Hey, I'm trying out javacord, but i keep getting an ExceptionInInitializerError even though I only copy'd your code and set everything up the way they should. 

`Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:109)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:116)
        at com.mashape.unirest.http.options.Options.refresh(Options.java:72)
        at com.mashape.unirest.http.options.Options.<clinit>(Options.java:46)
        at com.mashape.unirest.http.Unirest.setDefaultHeader(Unirest.java:123)
        at de.btobastian.javacord.Javacord.<clinit>(Javacord.java:45)
        at nl.rbhva.discordcalendar.App.main(App.java:12)
Caused by: org.apache.commons.logging.LogConfigurationException: java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl (Caused by java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl)
        at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1158)
        at org.apache.commons.logging.LogFactory$2.run(LogFactory.java:960)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.commons.logging.LogFactory.newFactory(LogFactory.java:957)
        at org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:624)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
        at org.apache.http.conn.ssl.AbstractVerifier.<init>(AbstractVerifier.java:60)
        at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<init>(AllowAllHostnameVerifier.java:43)
        at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<clinit>(AllowAllHostnameVerifier.java:45)
        ... 8 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1020)
        ... 16 more
`

I don't know if this is the right place to ask but what am I doing wrong?

Thanks in advance, 
Raphaël Bunck

**Comment by RaphaelBunck** [comment]
Compiling to a jar with mvn package and running with java -jar ... gave me this error. Running in ide seems to behave fine

**Comment by BtoBastian** [comment]
Do you use the minimizeJar option?

**Comment by RaphaelBunck** [comment]
Sorry this is probably my fault I know this issues section is not a live tech support :p

**Comment by BtoBastian** [comment]
Yes, this pretty much looks like an issue with your pom.xml file.
Can you please show the file to us?

**Comment by RaphaelBunck** [comment]
Here it is:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>nl.rbhva.discordcalendar</groupId>
    <artifactId>DiscordCalendar</artifactId>
    <version>1.0-SNAPSHOT</version>
    <pluginRepositories>
        <pluginRepository>
            <id>apache.snapshots</id>
            <url>http://repository.apache.org/snapshots/</url>
        </pluginRepository>
    </pluginRepositories>
    <repositories>
        <repository>
            <id>javacord-repo</id>
            <url>http://repo.bastian-oppermann.de</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>23.0</version>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.6</version>
        </dependency>
        <dependency>
            <groupId>de.btobastian.javacord</groupId>
            <artifactId>javacord</artifactId>
            <version>2.0.17</version>
            
            <classifier>shaded</classifier>
        </dependency>
        
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.3</version>
        </dependency>
        
        <dependency>
            <groupId>org.mnode.ical4j</groupId>
            <artifactId>ical4j</artifactId>
            <version>2.0.4</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.6</source>
                    <target>1.6</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <mainClass>nl.rbhva.discordcalendar.App</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <minimizeJar>false</minimizeJar>
                            <createDependencyReducedPom>true</createDependencyReducedPom>
                            <dependencyReducedPomLocation>
                                ${java.io.tmpdir}/dependency-reduced-pom.xml
                            </dependencyReducedPomLocation>
                            <relocations>
                                <relocation>
                                    <pattern>com.acme.coyote</pattern>
                                    <shadedPattern>hidden.coyote</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>`

It's a huge mess

**Comment by BtoBastian** [comment]
Try to change:
```xml
...
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-shade-plugin</artifactId>
<version>2.4</version>
<executions>
    <execution>
        <phase>package</phase>
        <goals>
            <goal>shade</goal>
        </goals>
        <configuration>
            <minimizeJar>false</minimizeJar>
            <createDependencyReducedPom>true</createDependencyReducedPom>
            <dependencyReducedPomLocation>
                ${java.io.tmpdir}/dependency-reduced-pom.xml
            </dependencyReducedPomLocation>
            <relocations>
                <relocation>
                    <pattern>com.acme.coyote</pattern>
                    <shadedPattern>hidden.coyote</shadedPattern>
                </relocation>
            </relocations>
        </configuration>
    </execution>
</executions>
</plugin>
...
```
to
```xml
...
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-shade-plugin</artifactId>
<version>2.4</version>
<executions>
    <execution>
        <phase>package</phase>
        <goals>
            <goal>shade</goal>
        </goals>
        <configuration>
            <minimizeJar>false</minimizeJar>
            <createDependencyReducedPom>true</createDependencyReducedPom>
            <dependencyReducedPomLocation>
                ${java.io.tmpdir}/dependency-reduced-pom.xml
            </dependencyReducedPomLocation>
            <relocations>
                <relocation>
                    <pattern>com.acme.coyote</pattern>
                    <shadedPattern>hidden.coyote</shadedPattern>
                </relocation>
            </relocations>
           <!-- This is new -->
            <artifactSet>
                <includes>
                    <include>de.btobastian.javacord:javacord</include>
                </includes>
            </artifactSet>
           <!-- This is new (end) -->
        </configuration>
    </execution>
</executions>
</plugin>
...
```

**Comment by RaphaelBunck** [comment]
I am now getting:
`Sep 10, 2017 9:11:02 PM de.btobastian.javacord.utils.JavacordLogger info
INFO: No SLF4J compatible logger was found. Using default javacord implementation!
Exception in thread "main" java.lang.NoClassDefFoundError: de/btobastian/sdcf4j/CommandExecutor
        at nl.rbhva.discordcalendar.App.main(App.java:12)
Caused by: java.lang.ClassNotFoundException: de.btobastian.sdcf4j.CommandExecutor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
`

I definitely imported sdc4j

**Comment by BtoBastian** [comment]
Just add it to the includes list, too (below `<include>de.btobastian.javacord:javacord</include>`)
```xml
<include>de.btobastian.sdcf4j:sdcf4j-core</include>
<include>de.btobastian.sdcf4j:sdcf4j-javacord</include>
```
